// Generated by Selenium IDE
import { Builder, By } from 'selenium-webdriver'
import 'dotenv/config'
import { goToLSG } from '../utilities.js'

describe('Expandable Search Input', function() {
  this.timeout(30000)
  let driver
  let vars

  let env = process.env.ENVIRONMENT
  let Component_URL = env == "QA" ? "https://axosbank-qa-sentry.outsystemsenterprise.com/AXOS_Reactive_LSG/PatternDetail?MenuCategoryId=8&MenuSubCategorId=122" : "https://axosbank-dev-sentry.outsystemsenterprise.com/AXOS_Reactive_LSG/PatternDetail?MenuCategoryId=8&MenuSubCategorId=122"

  let savedCookies = null;

  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('OpenTypeClose', async function() {
    await driver.manage().setTimeouts({ implicit: 10000 });
    savedCookies = await goToLSG(driver, Component_URL, savedCookies);

    await driver.findElement(By.css('i[aria-label="open search field"]')).click()
    await driver.findElement(By.css('input[placeholder="Search Here..."]')).sendKeys("hello")
    await driver.findElement(By.css('i[aria-label="close search field"]')).click()
    
  })

  it('OpenTypeClickOut', async function() {
    await driver.manage().setTimeouts({ implicit: 10000 });
    savedCookies = await goToLSG(driver, Component_URL, savedCookies);

    await driver.findElement(By.css('i[aria-label="open search field"]')).click()
    await driver.findElement(By.css('input[placeholder="Search Here..."]'))
    await driver.findElement(By.css('div.pattern-preview-header > div.heading6')).click()
    await driver.findElement(By.css('i[aria-label="open search field"]'))
  })

  it('OpenClose', async function() {
    await driver.manage().setTimeouts({ implicit: 10000 });
    savedCookies = await goToLSG(driver, Component_URL, savedCookies);

    await driver.findElement(By.css('i[aria-label="open search field"]')).click()
    await driver.findElement(By.css('input[placeholder="Search Here..."]'))
    await driver.findElement(By.css('i[aria-label="close search field"]')).click()
  })
})


